# Port du service Gateway, ce sera le point d'entrée public de votre application.
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://${PATIENT_HOST:localhost}:${PATIENT_PORT:8081}
          predicates:
            - Path=/patients/**

        - id: notes-service-route
          uri: http://${NOTES_HOST:localhost}:${NOTES_PORT:8082}
          predicates:
            - Path=/notes/**

        - id: report-service-route
          uri: http://${REPORT_HOST:localhost}:${REPORT_PORT:8083}
          predicates:
            - Path=/report/**